language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - "pip install -r requirements/base.txt --use-mirrors"
  - "pip install nose==1.2.1"
# command to run tests
script: nosetests
