language: python
python:
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - pip install -r requirements/base.txt --use-mirrors
  - pip install nose==1.2.1
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then 2to3 -w thebot; fi
# command to run tests
script: nosetests
